### ISSUE TITLE
Source password via variable

### ISSUE THREAD

**Issue by mkswebdev** [manticoresoftware/docker#15]
How hide password from `manticore.conf`? Can I use a variable?

docker-compose.yml:
```
version: "3.7"

networks:
    backend:
        driver: bridge

services:`
    manticore:
        image: manticoresearch/manticore
        restart: unless-stopped
        environment:
            - variable_sql_pass=${DB_ROOT_PASSWORD} <--- password from secret .env
        ports:
            - 127.0.0.1:9306:9306
        ulimits:
            ...
        depends_on:
            - db
        volumes:
            - ./docker/manticore:/etc/manticoresearch
        networks:
            - backend
```

./docker/manticore/manticore.conf:
```
source mysource
{
	type       = mysql
	sql_host   = db
	sql_user   = root
	sql_pass   = <---- password via variable possible?
	sql_db     = mydb
	sql_port   = 3306
}
...
```
