### ISSUE TITLE
Incorrect UTF-8 character display in stdout logs

### ISSUE THREAD

**Issue by KhAlena** [manticoresoftware/docker#20]
Russian search results are correct.
When logging to a file, the display of Russian letters is also correct.
But when redirecting query.log to /dev/stdout characters looks like on image:
![image](https://user-images.githubusercontent.com/58228114/176434122-cb648e2c-fe85-4adb-af87-29066e535093.png)

English letters displayed also correctly.

**Comment by sanikolaev** [comment]
Please provide more details on how to reproduce the issue and make sure there's no locale issue in the environment. So far I can't reproduce it like this:

```
msnikolaev@dev:~/issue_20$ cat docker-compose.yml
version: '2.2'

services:
  manticore:
    container_name: manticore
    image: manticoresearch/manticore
    restart: always
    ports:
      - 127.0.0.1:9315:9306
    ulimits:
      nproc: 65535
      nofile:
         soft: 65535
         hard: 65535
      memlock:
        soft: -1
        hard: -1
    environment:
      - QUERY_LOG_TO_STDOUT=true
      - searchd_query_log_format=plain
    volumes:
      - ./data:/var/lib/manticore
```

```
mysql> create table t(f text);
Query OK, 0 rows affected (0.01 sec)
mysql> select * from t where match('абв');
Empty set (0.00 sec)
```

```
snikolaev@dev:~/issue_20$ docker-compose up
Recreating manticore ... done
Attaching to manticore
manticore    | [Wed Jun 29 14:59:23.670 2022] [1] using config file '/etc/manticoresearch/manticore.conf' (9168 chars)...
manticore    | starting daemon version '5.0.2 348514c86@220530 dev' ...
manticore    | listening on all interfaces for mysql, port=9306
manticore    | listening on UNIX socket /var/run/mysqld/mysqld.sock
manticore    | listening on 192.168.240.2:9312 for sphinx and http(s)
manticore    | listening on all interfaces for sphinx and http(s), port=9308
manticore    | Manticore 5.0.2 348514c86@220530 dev
manticore    | Copyright (c) 2001-2016, Andrew Aksyonoff
manticore    | Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
manticore    | Copyright (c) 2017-2022, Manticore Software LTD (https://manticoresearch.com)
manticore    |
manticore    | precaching index 't'
manticore    | accepting connections
manticore    | prereading 1 indexes
manticore    | prereaded 1 indexes in 0.000 sec
manticore    | [Wed Jun 29 14:59:25.970 2022] 0.000 sec 0.000 sec [ext2/0/ext 0 (0,20)] [t] абв
```

**Comment by KhAlena** [comment]
docker-compose 
```
  # Search Service
  tamaranga-manticore:
    container_name: tamaranga-manticore
    image: tamaranga-manticore:${TAG:-latest}
    build:
      context: ./docker/manticore/
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - tamaranga-manticore:/var/lib/manticoresearch
    networks:
      - internal-network
    env_file:
      - .env
```
Dockerfile
```
FROM manticoresearch/manticore

ARG RU_PACK_URL=https://repo.manticoresearch.com/repository/morphology/ru.pak.tgz
ARG EN_PACK_URL=https://repo.manticoresearch.com/repository/morphology/en.pak.tgz
# Locales installation
RUN apt-get update
RUN apt-get install -y locales-all locales curl xz-utils manticore-columnar-lib
RUN locale-gen ru_RU.UTF-8

# Copy conf file
COPY manticore.conf /etc/manticoresearch/manticore.conf

# Prepare folder for Index files
RUN mkdir -pv /var/lib/manticoresearch
RUN chmod -R 777 /var/lib/manticoresearch

# Install ru.pack
RUN curl -LJO ${RU_PACK_URL}
RUN tar -xvzf ru.pak.tgz -C /usr/share/manticore
RUN rm ru.pak.tgz

# Install en.pack
RUN curl -LJO ${EN_PACK_URL}
RUN tar -xvzf en.pak.tgz -C /usr/share/manticore
RUN rm en.pak.tgz


CMD ["searchd", "--nodetach", "--config", "/etc/manticoresearch/manticore.conf"]
```
