### ISSUE TITLE
Add CI for CLT tests in docker

### ISSUE THREAD

**Issue by djklim87** [manticoresoftware/docker#48]

**Comment by djklim87** [comment]
Done, but because currently we have [Buddy issue](https://manticoresearch.slack.com/archives/C5EEXJG31/p1697869773521959), I can't add builds in dev mode. So need to not forget add lines below in build args
```
        build-args: |
          ARCH=amd
          DEV=1
```

**Comment by djklim87** [comment]
Decided that we should rewrite CI CLT to use DinD inside and write tests using complete docker commands

**Comment by djklim87** [comment]
Done in fc375209ef3e61eed37ba7e163ac7e470ec6e6b8

**Comment by sanikolaev** [comment]
Please rename the workflow:

```
name: k3s Testing
```

**Comment by sanikolaev** [comment]
A few more notes on:
```
      - uses: manticoresoftware/clt@main
        with:
          image: manticoresoftware/manticore-docker-test-kit:latest
          test_prefix: clt_tests/tests/
          run_args: --privileged -v ".:/docker/"
```

* it's better to use a specific version instead of `clt@main`
* do we need to push/pull the image at all? Looks like a waste of time and resources.
