### ISSUE TITLE
Cannot create directory ‘galera’: File exists

### ISSUE THREAD

**Issue by djklim87** [manticoresoftware/docker#85]
According Telegram issue https://t.me/manticore_chat/7198/10987

```
mkdir: cannot create directory ‘galera’: File exists
Manticore 6.2.13 4950f3d02@24020213 dev (columnar 2.2.5 214ce90@240115) (secondary 2.2.5 214ce90@240115) (knn 2.2.5 214ce90@240115)
Copyright (c) 2001-2016, Andrew Aksyonoff
Copyright (c) 2008-2016, Sphinx Technologies Inc (http://sphinxsearch.com)
Copyright (c) 2017-2024, Manticore Software LTD (https://manticoresearch.com)
```

**Comment by djklim87** [comment]
Part of docker-compose.yml

```
manticore:
    image: "manticoresearch/manticore:dev"
    environment:
      - EXTRA=1
      - CREATE_PLAIN_TABLES=delta_go_search_cache:*/15 * * * *;go_search_cache:0 3 * * *;go_search_cache;delta_go_search_cache;
      - SQL_MANTICORE_HOST=
      - SQL_MANTICORE_USER=
      - SQL_MANTICORE_PASS=
      - SQL_MANTICORE_DB=
      - SQL_MANTICORE_PORT=
    ports:
      - 9306:9306
      - 9308:9308
    volumes:
      - ./kube/manticore.conf:/etc/manticoresearch/manticore.conf
      - ./kube/manticore/data:/var/lib/manticore/data
```

**Comment by djklim87** [comment]
Config
```
#!/bin/sh

SQL_HOST="$SQL_MANTICORE_HOST"
SQL_USER="$SQL_MANTICORE_USER"
SQL_PASS="$SQL_MANTICORE_PASS"
SQL_DB="$SQL_MANTICORE_DB"
SQL_PORT="$SQL_MANTICORE_PORT"

ip=`hostname -i|rev|cut -d\  -f 1|rev`
cat << EOF
source s_DB
{
        type                    = mysql
        sql_host                = $SQL_HOST
        sql_user                = $SQL_USER
        sql_pass                = $SQL_PASS
        sql_db                  = $SQL_DB
        sql_port                = $SQL_PORT
        
        sql_query_pre           = SET NAMES utf8
}

source s_go_search_cache: s_DB
{
        sql_query               = SELECT (id * 100 + link_type) as id, id as link_id, link_type, keywords FROM go_search_cache
    
        sql_attr_uint           = link_id
        sql_attr_uint           = link_type
        sql_field_string        = keywords
}

source s_delta_go_search_cache: s_DB 
{
        sql_query               = SELECT (id * 100 + link_type) as id, id as link_id, link_type, keywords FROM go_search_cache WHERE mtime > UNIX_TIMESTAMP() - 3600

        sql_attr_uint           = link_id
        sql_attr_uint           = link_type
        sql_field_string        = keywords
}

index base
{
    type = template
    
    min_word_len        = 2
    min_infix_len       = 2
    
    index_exact_words   = 1
    index_sp            = 1
    html_strip          = 1
    blend_chars         = .,-
    
    charset_table       = 0..9, A..Z->a..z, _, +, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F, U+401->U+451, U+451    
    morphology          = lemmatize_ru_all
} 

index go_search_cache:base
{
    type                = plain
    source              = s_go_search_cache
    path                = /var/lib/manticore/data/go_search_cache
}

index delta_go_search_cache:base
{
    type                = plain
    source              = s_delta_go_search_cache
    path                = /var/lib/manticore/data/delta_go_search_cache
}

index idx_go_search_cache:base
{
    type                = rt
    source              = s_go_search_cache
    rt_mem_limit        = 128M
    path                = /var/lib/manticore/data/idx_go_search_cache
    preopen             = 1
    rt_field            = noname
}

index ab_company_search_cache:base
{
    type                = rt
    path                = /var/lib/manticore/data/ab_company_search_cache
    rt_attr_uint        = company_id
    rt_attr_uint        = addressbook_id
    rt_attr_string      = field

    rt_field            = search_cache
    stored_fields       = search_cache
    bigram_index        = all    
}

searchd
{
    listen                          = $ip:9312
    listen                          = $ip:9315-9325:replication
    listen                          = 9306:mysql41
    listen                          = 9308:http

    log                             = searchd.log
    pid_file                        = searchd.pid
    binlog_path                     =
    seamless_rotate                 = 1
    preopen_tables                  = 1
    unlink_old                      = 1
    max_packet_size                 = 16M
    max_filters                     = 256
    max_filter_values               = 4096
    max_batch_queries               = 32
    network_timeout                 = 5
    client_timeout                  = 300
    persistent_connections_limit    = 250

}

common {
    # lemmatizer_base = /usr/local/share
    # progressive_merge =
    # json_autoconv_keynames =
    # json_autoconv_numbers = 0
    # on_json_attr_error = ignore_attr
    # plugin_dir =
}

indexer
{
    mem_limit = 1024M
}
EOF
```

**Comment by djklim87** [comment]
I confirm that out docker image works fine in k8s. Useful ManticoreSearch deployment example provided below:

1. Create PVC with name `manticore-storage`
2. Pass ManticoreSearch config to ConfigMap:
```yaml
apiVersion: v1
data:
  manticore.conf: |
    source src {
     type = csvpipe
     csvpipe_command = echo "1,abc" && echo "2,abc" && echo "3,abc abc"
     csvpipe_field = f
    }
    index idx {
     type = plain
     source = src
     path = idx
     stored_fields = f
    }
kind: ConfigMap
metadata:
  name: manticore-config-map
```
3. Create Manticore deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: manticore
    run: manticore
  name: manticore-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manticore
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: manticore
        run: manticore
    spec:
      containers:
        - env:
            - name: EXTRA
              value: '1'
            - name: CREATE_PLAIN_TABLES
              value: idx:* * * * *;idx
            - name: searchd_listen
              value: >-
                9306:mysql41|/var/run/mysqld/mysqld.sock:mysql41|9308:http|$ip:9312|$ip:9315-9325:replication
            - name: searchd_pid_file
              value: /var/lib/manticore/searchd.pid
            - name: searchd_log
              value: /var/lib/manticore/searchd.log
          image: manticoresearch/manticore:dev-6.2.13-855e8ff
          imagePullPolicy: IfNotPresent
          name: manticore
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 256Mi
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          volumeMounts:
            - mountPath: /var/lib/manticore
              name: manticore-storage
            - mountPath: /etc/manticoresearch/manticore.conf
              name: manticore-config-volume
              subPath: manticore.conf
      restartPolicy: Always
      securityContext:
        fsGroup: 999
        runAsGroup: 999
        runAsUser: 999
      volumes:
        - name: manticore-storage
          persistentVolumeClaim:
            claimName: manticore-storage
        - emptyDir: {}
          name: shared-files
        - configMap:
            defaultMode: 420
            name: manticore-config-map
          name: manticore-config-volume
```
4. Confirm that everything works fine:
```mysql
show tables;
+-------+-------+
| Index | Type  |
+-------+-------+
| idx   | local |
+-------+-------+
select * from idx;
+------+---------+
| id   | f       |
+------+---------+
|    1 | abc     |
|    2 | abc     |
|    3 | abc abc |
+------+---------+
```
